# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEP_LOCATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'company_deptlocation',
            },
        ),
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('d_name', models.CharField(max_length=20, unique=True)),
                ('d_number', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('mgr_start_date', models.DateField()),
            ],
            options={
                'db_table': 'company_department',
            },
        ),
        migrations.CreateModel(
            name='DEPENDENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('b_date', models.DateField()),
                ('relationship', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'company_dependent',
            },
        ),
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('f_name', models.CharField(max_length=20)),
                ('m_init', models.CharField(max_length=5)),
                ('l_name', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('b_date', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('salary', models.IntegerField()),
                ('d_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.DEPARTMENT')),
                ('super_ssn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.EMPLOYEE')),
            ],
            options={
                'db_table': 'company_employee',
            },
        ),
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('p_name', models.CharField(max_length=20)),
                ('p_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('p_location', models.CharField(max_length=20)),
                ('d_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.DEPARTMENT')),
            ],
            options={
                'db_table': 'company_project',
            },
        ),
        migrations.CreateModel(
            name='WORKSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=20)),
                ('e_ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.EMPLOYEE')),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.PROJECT')),
            ],
            options={
                'db_table': 'company_workson',
            },
        ),
        migrations.AddField(
            model_name='dependent',
            name='e_ssn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.EMPLOYEE'),
        ),
        migrations.AddField(
            model_name='department',
            name='mgr_ssn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.EMPLOYEE'),
        ),
        migrations.AddField(
            model_name='dep_locations',
            name='d_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.DEPARTMENT'),
        ),
        migrations.AlterUniqueTogether(
            name='workson',
            unique_together=set([('e_ssn', 'pno')]),
        ),
        migrations.AlterUniqueTogether(
            name='dependent',
            unique_together=set([('e_ssn', 'dependent_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='dep_locations',
            unique_together=set([('d_number', 'd_location')]),
        ),
    ]
